### ISSUE TITLE
Not accepting HTTP connections

### ISSUE THREAD

**Issue by TomFaulkner** [meti-/dockerPiHole#3]
I ran with the following:
sudo docker run --name pihole -e ADMIN_PASS="reallysecurepassword" -e ServerIP="192.168.1.20" lplab/pihole:latest

Neither the webserver or the DNS server is accepting connections (connection refused, even from the host system). If I use docker exec and run bash in the container I can do curl and nslookup on localhost and it does answer. Is there something I need to do to get the server to accept outside connections? The IP I'm using in ServerIP is the IP of the machine running docker.

**Comment by Nesousx** [comment]
Hi,

You are not exposing any HTTP port (nor the DNS ones). Try exposing them with:   -p 53:53 -p 53:53/udp -p 80:80
