### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by vitoriosassi** [meti-/dockerPiHole#4]
I'm trying running lp-lab/dockerPiHole on raspberry ARMv7 Processor rev 4 (v7l) 
Docker version: Docker version 18.06.0-ce, build 0ffa825

After pull the container on docker hub and start like 

$docker run -p 53:53/tcp -p 53:53/udp -p 80:80/tcp -d -e DNS1="8.8.8.8" -e DNS2="8.8.4.4" lplab/pihole 

I've got this error:
$docker logs a257dfcdf36d
standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by lpian24** [comment]
Well, you get that because it's not an ARM image

**Comment by vitoriosassi** [comment]
Yeah, I’m figured out that, sorry to bored you with this topic.
Thanks.


Vitorio Sassi
